In [2]:
import cv2
#import numpy as np
#import matplotlib.pyplot as plt
img=  cv2.imread("image1.jpg",1)#GRAYSCALE=0
print(img)
#cv2.imshow('image',img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
#cv2.imwrite('grayscale.jpg', img)

[[[27 25 25]
  [27 25 24]
  [26 25 21]
  ...
  [38 67 76]
  [39 68 75]
  [39 68 75]]

 [[27 25 24]
  [27 25 24]
  [26 25 21]
  ...
  [38 67 76]
  [39 68 75]
  [39 68 75]]

 [[27 26 22]
  [27 26 22]
  [27 27 21]
  ...
  [38 67 76]
  [39 68 75]
  [39 68 75]]

 ...

 [[21 18  3]
  [21 18  3]
  [21 18  3]
  ...
  [29 35 40]
  [30 33 38]
  [25 31 36]]

 [[21 18  3]
  [21 18  3]
  [21 18  3]
  ...
  [28 34 39]
  [29 32 37]
  [27 31 36]]

 [[21 18  3]
  [21 18  3]
  [21 18  3]
  ...
  [30 34 39]
  [29 32 37]
  [27 31 36]]]


0